export const reference_liste_all = [
    'Davis, Justin (10 October 2013). <span class="wiki_link">"Inside Cookie Clicker and the Idle Game Movement"</span>. IGN. Archived from the original on 11 October 2013. Retrieved 2 April 2014.',
    'Kiberd, Roisin (January 2016). <span class="wiki_link">"Cookie Clicker, the Internets most pointlessly addictive game, is also its most subversive"</span>. The Kernel. The Daily Dot. Archived from the original on 20 October 2018. Retrieved 23 February 2021.',
    'Koch, Cameron (10 August 2021). <span class="wiki_link">"Cookie Clicker Is Getting More Than 500 Achievements For Its Steam Release"</span>. GameSpot. Archived from the original on 10 August 2021. Retrieved 13 May 2023.',
    'Shutler, Ali (6 September 2021). <span class="wiki_link">"Cookie Clicker has quickly become one of the most popular games on Steam"</span>. NME. Archived from the original on 1 November 2021. Retrieved 1 May 2023.',
    'Bogost, Ian (2016). <span class="wiki_link">Play Anything: The Pleasure of Limits, the Uses of Boredom, and the Secret of Games</span>. Hachette. ISBN 9780465096503.',
    'Orteil. Retrieved 13 June 2016',
    'Thiennot, Julien. <span class="wiki_link">"Cookie Clicker > Info"</span>. Dashnet. Retrieved 29 July 2017.',
    '<span class="wiki_link">"Dashnet Patreon"</span>. Patreon. Retrieved 5 November 2019.',
    '<span class="wiki_link">"Twitter / Orteil: weve just made the Cookie Clicker android version public for beta-testing ..."</span> Twitter. Retrieved 5 November 2019.',
    '<span class="wiki_link">"Idle Game Maker Documentation"</span>. Orteil.dashnet.org. Retrieved 10 July 2014.',
    ' Julien Thiennot [@Orteil42] (8 August 2021). <span class="wiki_link">"were aiming for a September 1st release at $4.99, you can already wishlist it on Steam! more details coming soon, thank you for supporting us all these years. weve got a ton more stuff planned"</span> (Tweet). Archived from the original on 8 August 2021. Retrieved 13 May 2023 - via Twitter.',
    'Rosenfeld, Daniel [@C418] (8 August 2021). <span class="wiki_link">"In case you missed it, Ive worked on a brand new soundtrack for Cookie Clicker 🍪"</span> (Tweet). Archived from the original on 8 August 2021. Retrieved 13 May 2023 - via Twitter.',
    'Dzakic, Merima (1 September 2021). <span class="wiki_link">"Cookie Clicker crumbles onto Steam - the classic idle game now live"</span>. altchar. Archived from the original on 1 September 2021. Retrieved 1 September 2021.',
    ' Ruffino, Paolo (2016). <span class="wiki_link">"Games to Live With"</span>. Digital Culture & Society. 2 (1/2016): 156. doi:10.14361/dcs-2016-0111. ISBN 9783839432105. S2CID 62087760. Retrieved 29 July 2017.',
    ' Crecente, Brian (30 September 2013). <span class="wiki_link">"The cult of the cookie clicker: When is a game not a game?"</span>. Polygon. Archived from the original on 3 October 2013. Retrieved 1 November 2013.',
    ' King, Austin (19 October 2020). <span class="wiki_link">"How Long Cookie Clicker Takes To Beat (& What Happens)"</span>. Screen Rant. Archived from the original on 23 October 2021. Retrieved 17 May 2023.',
    ' Ashworth, Mack (7 September 2021). <span class="wiki_link">"Cookie Clicker Steam Review: The definitive version thats worth paying for"</span>. GameRevolution. Archived from the original on 7 September 2021. Retrieved 19 May 2023.',
    ' Boing, Boing (2 December 2013). <span class="wiki_link">"Distract yourself with free browser games"</span>. Boing Boing. Retrieved 12 May 2015.',
    ' Makedonski, Brett (25 September 2013). <span class="wiki_link">"Cookie Clicker gets inside your psychological kitchen"</span>. Destructoid. Archived from the original on 26 September 2013. Retrieved 29 September 2013.',
    ' Hodge, James J. (2019), <span class="wiki_link">"Out of Hand: Animation, Technics, History"</span>, Sensations of History - Animation and New Media Art, University of Minnesota Press, ISBN 978-1452960586',
    ' <span class="wiki_link">"Professor Sebastian Deterding"</span>. Imperial College London. Archived from the original on 2 July 2022. Retrieved 16 January 2023.',
    ' Deterding, Sebastian (26 March 2019). <span class="wiki_link">"Cookie Clicker: Gamification"</span>. In Huntermann, Nina B; Payne, Matthew Thomas (eds.). How to Play Video Games. NYU Press. pp. 200-207. ISBN 9781479802142.',

]